# Generated by Django 5.1.5 on 2025-01-24 16:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('discount', models.PositiveIntegerField(default=0, null=True)),
                ('featured_image', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('total', models.PositiveIntegerField(default=0, null=True)),
                ('available', models.PositiveIntegerField(default=0, null=True)),
                ('image', models.ImageField(upload_to='productsimage')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('product_information', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tags', models.CharField(default='', max_length=200)),
                ('slug', models.CharField(blank=True, max_length=555, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecapp.category')),
            ],
        ),
    ]
