# Generated by Django 5.1.5 on 2025-01-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0005_remove_product_image_additional_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
