# Generated by Django 5.1.5 on 2025-01-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0006_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
