# Generated by Django 5.1.5 on 2025-01-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0008_alter_product_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_image',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='additional_images/'),
        ),
    ]
