# Generated by Django 5.1.5 on 2025-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0009_alter_additional_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_image',
            name='images',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
