# Generated by Django 5.1.5 on 2025-01-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0010_alter_additional_image_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional_image',
            name='images',
        ),
        migrations.AddField(
            model_name='additional_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='additional_images/'),
        ),
    ]
