# Generated by Django 5.1.5 on 2025-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0011_remove_additional_image_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional_image',
            name='image',
        ),
        migrations.AddField(
            model_name='additional_image',
            name='images',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
